default :
  Input :    
    Discovery dataset name :
    Expression matrix :     
    Annotation file : 
    Annotation file column to scale by : NULL
    Annotation file column(s) to plot : []
    
  Output :
    Output folder : 

  Pipeline settings :
    #Pipeline steps:
    #   step 1 (extract cell type specific genes)
    #   step 2 (cell state discovery on correrlation matrices)
    #   step 3 (choosing the number of cell states)
    #   step 4 (extracting cell state information)
    #   step 5 (cell state re-discovery in expression matrices)
    #   step 6 (extracting information for re-discovered cell states)
    #   step 7 (cell state QC filter)
    #   step 8 (ecotype discovery)
    Pipeline steps to skip : [25, 1, 2, 3, 4, 7] 
    Filter non cell type specific genes : True
    Number of threads : 16
    Number of NMF restarts : 5
    Maximum number of states per cell type : 15
    Cophenetic coefficient cutoff : 0.975
    #The p-value cutoff used for filtering non-significant overlaps in the jaccard matrix used for discovering ecotypes in step 8. Default: 1 (no filtering).
    Jaccard matrix p-value cutoff : 1
    Minimum number of states in ecotypes : 3

  PDSM Settings :
    Annotation File : 
    Expression Matrix : 
    Input Folder : 
    States Output Folder : 
    Ecotypes Output Folder : 
    P-Value Cutoff : 0.05
    Minimum States Per Ecotype: 3

    
